import { Sun, Shirt, Wand2, BarChart2, Sparkles } from 'lucide-react';

export const GLOBAL_CSS = `
  /* Hide scrollbars while keeping scroll behaviour */
  .scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }
  .scrollbar-hide::-webkit-scrollbar { display: none; }

  /* Modal slide-up (mobile) */
  @keyframes slideUp {
    from { transform: translateY(100%); opacity: 0; }
    to   { transform: translateY(0);    opacity: 1; }
  }
  /* Modal fade-scale-in (desktop) */
  @keyframes fadeScaleIn {
    from { opacity: 0; transform: scale(0.97) translateY(6px); }
    to   { opacity: 1; transform: scale(1)    translateY(0);   }
  }
  /* Backdrop */
  @keyframes backdropIn {
    from { opacity: 0; }
    to   { opacity: 1; }
  }

  .modal-animate   { animation: slideUp     0.32s cubic-bezier(0.32, 0.72, 0, 1) forwards; }
  .backdrop-fade   { animation: backdropIn  0.2s ease forwards; }

  @media (min-width: 768px) {
    .modal-animate { animation: fadeScaleIn 0.2s ease-out forwards; }
  }

  /* Location badge transitions */
  .loc-pill  { transition: max-width 0.28s cubic-bezier(0.4,0,0.2,1), opacity 0.22s ease; }
  .loc-input { transition: max-width 0.28s cubic-bezier(0.4,0,0.2,1), opacity 0.22s ease; }

  /* Outfit carousel transitions */
  @keyframes outfitSlideRight { from { opacity: 0; transform: translateX(28px); } to { opacity: 1; transform: translateX(0); } }
  @keyframes outfitSlideLeft  { from { opacity: 0; transform: translateX(-28px); } to { opacity: 1; transform: translateX(0); } }
  @keyframes outfitFade       { from { opacity: 0; } to { opacity: 1; } }
  .outfit-enter-right { animation: outfitSlideRight 0.32s cubic-bezier(0.25, 0.46, 0.45, 0.94) both; }
  .outfit-enter-left  { animation: outfitSlideLeft  0.32s cubic-bezier(0.25, 0.46, 0.45, 0.94) both; }
  .outfit-text-fade   { animation: outfitFade       0.25s ease-out both; }

  @keyframes cardExit {
    from { opacity: 1; transform: scale(1); }
    to   { opacity: 0; transform: scale(0.88); }
  }
  .card-exit { animation: cardExit 0.28s ease-in forwards; pointer-events: none; }
`;

export const BOARDS = ['All', 'Workwear', 'Weekend', 'Evening', 'Basics', 'Outerwear'];

export const PRESET_LOCATIONS = [
  { city: 'New York, NY',    lat: 40.7128,  lon: -74.0060,  weather: { tempF: 38, conditionLabel: 'Overcast',      highF: 44, lowF: 31, laterCondition: null      } },
  { city: 'Los Angeles, CA', lat: 34.0522,  lon: -118.2437, weather: { tempF: 73, conditionLabel: 'Clear',         highF: 78, lowF: 64, laterCondition: null      } },
  { city: 'Miami, FL',       lat: 25.7617,  lon: -80.1918,  weather: { tempF: 86, conditionLabel: 'Partly Cloudy', highF: 90, lowF: 79, laterCondition: 'Showers' } },
  { city: 'Chicago, IL',     lat: 41.8781,  lon: -87.6298,  weather: { tempF: 26, conditionLabel: 'Snow',          highF: 31, lowF: 20, laterCondition: null      } },
  { city: 'Seattle, WA',     lat: 47.6062,  lon: -122.3321, weather: { tempF: 52, conditionLabel: 'Rain',          highF: 56, lowF: 46, laterCondition: null      } },
];

export const CATEGORIES = [
  'Tops',
  'Bottoms',
  'Dresses & Jumpsuits',
  'Outerwear',
  'Knitwear & Sweaters',
  'Shoes',
  'Activewear / Athleisure',
  'Accessories & Bags',
  'Jewelry',
  'Underwear & Sleepwear',
  'Other',
];

export const ITEMS = [
  {
    id: 1,
    name: 'Structured Leather Tote',
    brand: '—',
    price: '$280',
    material: 'Grained Leather',
    category: 'Accessories & Bags',
    boards: ['Workwear', 'Weekend'],
    color: 'Chocolate Brown',
    size: 'OS',
    image: '/demo/245-DEERCOW-MARRON_FRONT.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#5C3A1E', colorFamily: 'Brown', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 2,
    name: 'CC Crystal Cuff',
    brand: 'Chanel',
    price: '$2,800',
    material: 'Lambskin & Crystal',
    category: 'Jewelry',
    boards: ['Evening'],
    color: 'Blush',
    size: 'OS',
    image: '/demo/Chanel.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#F0DDD4', colorFamily: 'Pink', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 3,
    name: 'CC Cashmere Beanie',
    brand: 'Chanel',
    price: '$1,300',
    material: '100% Cashmere',
    category: 'Accessories & Bags',
    boards: ['Weekend'],
    color: 'Ivory',
    size: 'OS',
    image: '/demo/Chanel_-_Chasmere_Beanie_($1,300).png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'warm' },
    colorProfile: { primaryHex: '#F5F0E6', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 4,
    name: 'Camellia Rain Boot',
    brand: 'Chanel',
    price: '$1,450',
    material: 'Rubber & Patent',
    category: 'Shoes',
    boards: ['Weekend', 'Outerwear'],
    color: 'Black',
    size: '38',
    image: "/demo/Chanel_Women's_Boots.png",
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 5,
    name: 'Classic Denim Jacket',
    brand: '—',
    price: '$85',
    material: '100% Cotton Denim',
    category: 'Outerwear',
    boards: ['Weekend', 'Basics'],
    color: 'Medium Wash Blue',
    size: 'S',
    image: '/demo/Classic_jean_jacket.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'outer', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#6B8CAD', colorFamily: 'Blue', undertone: 'Cool', vibrancy: 'Muted' },
  },
  {
    id: 6,
    name: 'Fine Knit Cardigan',
    brand: 'H&M',
    price: '$35',
    material: 'Fine Knit Polyamide Blend',
    category: 'Knitwear & Sweaters',
    boards: ['Weekend', 'Basics'],
    color: 'Pale Yellow',
    size: 'S',
    image: '/demo/Gilet_en_maille_fine_-_Jaune_clair_-_ENFANT___H&M_FR.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'mid', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F5EBA0', colorFamily: 'Yellow', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 7,
    name: 'Floral Pleated Charmeuse Skirt',
    brand: 'Lauren Ralph Lauren',
    price: '$165',
    material: '100% Polyester Charmeuse',
    category: 'Bottoms',
    boards: ['Evening', 'Weekend'],
    color: 'Floral Multi',
    size: 'S',
    image: '/demo/Lauren_Ralph_Lauren_Floral_Pleated_Satin_Charmeuse_Skirt.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#7B4F6E', colorFamily: 'Purple', undertone: 'Cool', vibrancy: 'Muted' },
  },
  {
    id: 8,
    name: 'Lucilla Shirt Dress',
    brand: 'Cinq à Sept',
    price: '$395',
    material: 'Stretch Crepe',
    category: 'Dresses & Jumpsuits',
    boards: ['Workwear', 'Evening'],
    color: 'Navy',
    size: 'XS',
    image: '/demo/Lucilla_Dress.png',
    ratio: 'portrait',
    liked: true,
    attributes: { layerType: 'none', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#1A2744', colorFamily: 'Blue', undertone: 'Cool', vibrancy: 'Deep' },
  },
  {
    id: 9,
    name: 'Polka Dot Midi Skirt',
    brand: 'Ralph Lauren',
    price: '$225',
    material: 'Silk Blend',
    category: 'Bottoms',
    boards: ['Workwear', 'Weekend'],
    color: 'Black & White',
    size: '6',
    image: '/demo/Ralph_Lauren.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 10,
    name: 'Kaida Boot-Cut Jean',
    brand: 'Ralph Lauren Collection',
    price: '$450',
    material: 'Stretch Denim',
    category: 'Bottoms',
    boards: ['Weekend', 'Workwear'],
    color: 'White',
    size: '26',
    image: '/demo/Ralph_Lauren_Collection___Kaida_White_Boot-Cut_Jeans___Autumn_•_Winter_Fashion.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F5F2EC', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Pastel' },
  },
  {
    id: 11,
    name: 'Flared Sleeve Silk Top',
    brand: 'Reformation',
    price: '$298',
    material: '100% Silk',
    category: 'Tops',
    boards: ['Evening', 'Weekend'],
    color: 'Army Green',
    size: 'XS',
    image: '/demo/Reformation_Flared_Sleeve_Silk_Top_-_Green.png',
    ratio: 'portrait',
    liked: true,
    attributes: { layerType: 'base', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#4A5C38', colorFamily: 'Green', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 12,
    name: 'Super Puff Long Coat',
    brand: 'Aritzia',
    price: '$375',
    material: 'Recycled Nylon & Down Fill',
    category: 'Outerwear',
    boards: ['Outerwear', 'Weekend'],
    color: 'Black',
    size: 'XS',
    image: '/demo/Super Puff Long.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'outer', sleeveLength: 'long', warmthRating: 'heavy' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 13,
    name: 'The Icon Watch',
    brand: 'Hanan Maybin',
    price: '$475',
    material: 'Gold-Tone Steel & Leather',
    category: 'Accessories & Bags',
    boards: ['Workwear', 'Evening', 'Weekend'],
    color: 'Gold',
    size: 'OS',
    image: '/demo/THE_ICON_WATCH.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#C9A84C', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 14,
    name: 'Double T-Buckle Pump',
    brand: 'Tory Burch',
    price: '$358',
    material: 'Leather',
    category: 'Shoes',
    boards: ['Workwear', 'Evening'],
    color: 'Black',
    size: '8',
    image: "/demo/Tory_Burch_Double_T-Buckle_Pump_80_mm_High_Women's_Heels_Perfect_Black_Perfect_Black___10_M,_Leather.png",
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 15,
    name: 'Bow Mini Dress',
    brand: 'Valentino Garavani',
    price: '$3,200',
    material: 'Virgin Wool',
    category: 'Dresses & Jumpsuits',
    boards: ['Evening'],
    color: 'Red',
    size: 'IT 42',
    image: '/demo/Valentino_Garavani_Multicolor_Virgin_Wool_Short_Dress_-_IT42.png',
    ratio: 'portrait',
    liked: true,
    attributes: { layerType: 'none', sleeveLength: 'short', warmthRating: 'medium' },
    colorProfile: { primaryHex: '#C41E3A', colorFamily: 'Red', undertone: 'Warm', vibrancy: 'Vivid' },
  },
  {
    id: 16,
    name: 'Embroidered Beaded Blouse',
    brand: 'Zara',
    price: '$69',
    material: 'Tulle & Silk Blend',
    category: 'Tops',
    boards: ['Evening'],
    color: 'Cream',
    size: 'S',
    image: '/demo/Zara_Tops___Embroidered_Beaded_Structure_Blouse_Zara_Cream_Floral_Embroidered_Blouse___Color__Cream___Size__S.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F0E8D5', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 17,
    name: 'CC Quilted Ballet Flat',
    brand: 'Chanel',
    price: '$1,250',
    material: 'Quilted Lambskin',
    category: 'Shoes',
    boards: ['Workwear', 'Weekend', 'Evening'],
    color: 'Black',
    size: '38',
    image: '/demo/blackchanelflats.png',
    ratio: 'square',
    liked: true,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 18,
    name: 'High-Rise Flare Pant',
    brand: '—',
    price: '$95',
    material: 'Stretch Denim',
    category: 'Bottoms',
    boards: ['Workwear', 'Evening', 'Weekend'],
    color: 'Black',
    size: '26',
    image: '/demo/blackpants.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 19,
    name: 'Wrap Tie Blouse',
    brand: '—',
    price: '$88',
    material: 'Cotton Poplin',
    category: 'Tops',
    boards: ['Workwear', 'Weekend'],
    color: 'Light Blue',
    size: 'S',
    image: '/demo/bluelong.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#A8C4D8', colorFamily: 'Blue', undertone: 'Cool', vibrancy: 'Pastel' },
  },
  {
    id: 20,
    name: 'Camellia Leather Jacket',
    brand: 'Chanel',
    price: '$8,500',
    material: 'Lambskin Leather',
    category: 'Outerwear',
    boards: ['Outerwear', 'Evening', 'Weekend'],
    color: 'Black',
    size: '36 FR',
    image: '/demo/camellia leather jacket.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'outer', sleeveLength: 'long', warmthRating: 'medium' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 21,
    name: 'Cashmere Turtleneck',
    brand: '—',
    price: '$420',
    material: '100% Cashmere',
    category: 'Knitwear & Sweaters',
    boards: ['Basics', 'Weekend'],
    color: 'Ivory',
    size: 'S',
    image: '/demo/cashmeresweater.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'mid', sleeveLength: 'long', warmthRating: 'warm' },
    colorProfile: { primaryHex: '#F5F0E6', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 22,
    name: 'Oversized Sunglasses',
    brand: 'Chanel',
    price: '$520',
    material: 'Acetate',
    category: 'Accessories & Bags',
    boards: ['Weekend', 'Evening'],
    color: 'Black',
    size: 'OS',
    image: '/demo/chanelglasses.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 23,
    name: 'One-Shoulder Charmeuse Top',
    brand: '—',
    price: '$110',
    material: 'Silk Charmeuse',
    category: 'Tops',
    boards: ['Evening', 'Weekend'],
    color: 'Olive',
    size: 'XS',
    image: '/demo/charmeuse olive top.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#4A5C30', colorFamily: 'Green', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 24,
    name: 'Dark Wash Bootcut Jean',
    brand: '—',
    price: '$98',
    material: 'Stretch Denim',
    category: 'Bottoms',
    boards: ['Weekend', 'Basics'],
    color: 'Dark Indigo',
    size: '26',
    image: '/demo/darkjeans.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#1E2F4A', colorFamily: 'Blue', undertone: 'Cool', vibrancy: 'Deep' },
  },
  {
    id: 25,
    name: 'Crochet Knit Midi Dress',
    brand: 'Sandro',
    price: '$490',
    material: 'Cotton Crochet Knit',
    category: 'Dresses & Jumpsuits',
    boards: ['Weekend', 'Evening'],
    color: 'Pale Yellow',
    size: 'XS',
    image: '/demo/dress.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'short', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F5E9A0', colorFamily: 'Yellow', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 26,
    name: 'Light Wash Flare Jean',
    brand: '—',
    price: '$88',
    material: 'Stretch Denim',
    category: 'Bottoms',
    boards: ['Weekend', 'Basics'],
    color: 'Light Wash Blue',
    size: '26',
    image: '/demo/flare jeans.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#9DB8D0', colorFamily: 'Blue', undertone: 'Cool', vibrancy: 'Pastel' },
  },
  {
    id: 27,
    name: 'Super-Star Sneaker',
    brand: 'Golden Goose',
    price: '$575',
    material: 'Leather & Glitter',
    category: 'Shoes',
    boards: ['Weekend', 'Basics'],
    color: 'White & Gold',
    size: '38',
    image: '/demo/ggsneaker.png',
    ratio: 'square',
    liked: true,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#F5F0E6', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 28,
    name: 'Belted Knit Maxi Dress',
    brand: '—',
    price: '$195',
    material: 'Wool Bouclé Knit',
    category: 'Dresses & Jumpsuits',
    boards: ['Evening', 'Weekend'],
    color: 'Oatmeal',
    size: 'XS',
    image: '/demo/knitdress.png',
    ratio: 'tall',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'long', warmthRating: 'medium' },
    colorProfile: { primaryHex: '#D8CCBA', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 29,
    name: 'Off-Shoulder Knit Top',
    brand: 'Michael Kors',
    price: '$198',
    material: 'Ribbed Knit',
    category: 'Tops',
    boards: ['Workwear', 'Evening'],
    color: 'Black',
    size: 'XS',
    image: '/demo/michael_kors_top_.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 30,
    name: 'Crystal-Heel Mary Jane',
    brand: 'Miu Miu',
    price: '$1,190',
    material: 'Satin & Crystal',
    category: 'Shoes',
    boards: ['Evening'],
    color: 'Olive Green',
    size: '38',
    image: '/demo/miumiu.png',
    ratio: 'square',
    liked: true,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#6B7A3A', colorFamily: 'Green', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 31,
    name: 'Ojima Ruffle Top',
    brand: 'Isabel Marant',
    price: '$460',
    material: 'Silk Chiffon',
    category: 'Tops',
    boards: ['Evening', 'Weekend'],
    color: 'Blush',
    size: 'XS',
    image: '/demo/ojima top.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#E8C4B8', colorFamily: 'Pink', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 32,
    name: 'Polka Dot Cap-Sleeve Top',
    brand: '—',
    price: '$55',
    material: 'Jersey',
    category: 'Tops',
    boards: ['Weekend', 'Workwear'],
    color: 'Cream & Black',
    size: 'S',
    image: '/demo/polkadot.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'short', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F5F0E0', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 33,
    name: 'Black Ribbed Turtleneck',
    brand: 'Ralph Lauren',
    price: '$195',
    material: 'Merino Wool Rib Knit',
    category: 'Knitwear & Sweaters',
    boards: ['Basics', 'Workwear', 'Weekend'],
    color: 'Black',
    size: 'XS',
    image: '/demo/rlblacksweater.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'mid', sleeveLength: 'long', warmthRating: 'warm' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 34,
    name: 'Burgundy Ribbed Turtleneck',
    brand: 'Ralph Lauren',
    price: '$195',
    material: 'Merino Wool Rib Knit',
    category: 'Knitwear & Sweaters',
    boards: ['Basics', 'Weekend'],
    color: 'Burgundy',
    size: 'XS',
    image: '/demo/rlburgundysweater.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'mid', sleeveLength: 'long', warmthRating: 'warm' },
    colorProfile: { primaryHex: '#5C1A2A', colorFamily: 'Red', undertone: 'Cool', vibrancy: 'Deep' },
  },
  {
    id: 35,
    name: 'Shearling Wrap Coat',
    brand: '—',
    price: '$850',
    material: 'Shearling Lamb',
    category: 'Outerwear',
    boards: ['Outerwear', 'Weekend'],
    color: 'Camel',
    size: 'S',
    image: '/demo/shearling coat.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'outer', sleeveLength: 'long', warmthRating: 'heavy' },
    colorProfile: { primaryHex: '#C4A882', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 36,
    name: 'Draped Silk Top',
    brand: '—',
    price: '$130',
    material: '100% Silk',
    category: 'Tops',
    boards: ['Evening', 'Workwear'],
    color: 'Ivory',
    size: 'XS',
    image: '/demo/silk top.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'base', sleeveLength: 'none', warmthRating: 'light' },
    colorProfile: { primaryHex: '#F5F0E0', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Pastel' },
  },
  {
    id: 37,
    name: 'Suede Flare Pant',
    brand: '—',
    price: '$375',
    material: 'Genuine Suede',
    category: 'Bottoms',
    boards: ['Weekend', 'Evening'],
    color: 'Camel',
    size: '26',
    image: '/demo/suedejeans.png',
    ratio: 'portrait',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'medium' },
    colorProfile: { primaryHex: '#C4A06A', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 38,
    name: 'Ava Top-Handle Bag',
    brand: 'Teddy Blake',
    price: '$625',
    material: 'Pebbled Leather',
    category: 'Accessories & Bags',
    boards: ['Workwear', 'Weekend', 'Evening'],
    color: 'Cream',
    size: 'OS',
    image: '/demo/teddyblakeava.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#D8CDB8', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 39,
    name: 'Westminster Trench Coat',
    brand: 'Burberry',
    price: '$2,290',
    material: 'Cotton Gabardine',
    category: 'Outerwear',
    boards: ['Outerwear', 'Workwear', 'Weekend'],
    color: 'Honey',
    size: 'UK 8',
    image: '/demo/trench coat.png',
    ratio: 'tall',
    liked: true,
    attributes: { layerType: 'outer', sleeveLength: 'long', warmthRating: 'light' },
    colorProfile: { primaryHex: '#C8922A', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
  {
    id: 40,
    name: 'Cera Suede Ankle Boot',
    brand: 'Veronica Beard',
    price: '$495',
    material: 'Suede',
    category: 'Shoes',
    boards: ['Weekend', 'Workwear'],
    color: 'Black',
    size: '38',
    image: '/demo/veronicabeardceraboots.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#1A1A1A', colorFamily: 'Neutral', undertone: 'Neutral', vibrancy: 'Deep' },
  },
  {
    id: 41,
    name: 'Raffia Wedge Sandal',
    brand: 'Jimmy Choo',
    price: '$745',
    material: 'Raffia & Metallic Leather',
    category: 'Shoes',
    boards: ['Evening', 'Weekend'],
    color: 'Gold',
    size: '38',
    image: '/demo/wedges.png',
    ratio: 'square',
    liked: false,
    attributes: { layerType: 'none', sleeveLength: 'none', warmthRating: 'none' },
    colorProfile: { primaryHex: '#C4A456', colorFamily: 'Neutral', undertone: 'Warm', vibrancy: 'Muted' },
  },
];

// Static wear logs used in demo/preview mode — realistic spread over ~90 days
export const DEMO_WEAR_LOGS = [
  { worn_date: '2026-06-20', item_ids: ['17','18','33','39','20'] },
  { worn_date: '2026-06-17', item_ids: ['17','26','36','27'] },
  { worn_date: '2026-06-13', item_ids: ['14','18','29','39'] },
  { worn_date: '2026-06-10', item_ids: ['17','37','33','20'] },
  { worn_date: '2026-06-07', item_ids: ['17','18','36','27','3'] },
  { worn_date: '2026-06-04', item_ids: ['14','9','19','39'] },
  { worn_date: '2026-06-01', item_ids: ['17','18','33','20'] },
  { worn_date: '2026-05-28', item_ids: ['27','24','36','39'] },
  { worn_date: '2026-05-24', item_ids: ['17','18','33','27'] },
  { worn_date: '2026-05-21', item_ids: ['14','37','16','39','3'] },
  { worn_date: '2026-05-18', item_ids: ['17','18','36','20'] },
  { worn_date: '2026-05-15', item_ids: ['17','26','33','27'] },
  { worn_date: '2026-05-11', item_ids: ['14','18','29','39','3'] },
  { worn_date: '2026-05-07', item_ids: ['17','24','36','20'] },
  { worn_date: '2026-05-03', item_ids: ['27','18','33','39'] },
  { worn_date: '2026-04-29', item_ids: ['17','37','19','20'] },
  { worn_date: '2026-04-25', item_ids: ['17','18','36','27'] },
  { worn_date: '2026-04-21', item_ids: ['14','9','33','39'] },
  { worn_date: '2026-04-17', item_ids: ['17','18','36','20'] },
  { worn_date: '2026-04-13', item_ids: ['27','24','33','39'] },
];

export const TABS = [
  { id: 'today',     label: 'Today',      Icon: Sun       },
  { id: 'wardrobe',  label: 'Wardrobe',   Icon: Shirt     },
  { id: 'studio',    label: 'Studio',     Icon: Wand2     },
  { id: 'analytics', label: 'Analytics',  Icon: BarChart2 },
  { id: 'stylist',   label: 'AI Stylist', Icon: Sparkles  },
];

export const RATIO = {
  tall:     'aspect-[2/3]',
  portrait: 'aspect-[3/4]',
  square:   'aspect-square',
};

export function countByBoard(items, board) {
  return board === 'All' ? items.length : items.filter(i => i.boards.includes(board)).length;
}

export const OUTFIT_GOALS = [
  { id: 'workwear',  label: 'Workwear',          emoji: '💼' },
  { id: 'casual',   label: 'Casual day-looks',   emoji: '☀️' },
  { id: 'night',    label: 'Night looks',         emoji: '🌙' },
  { id: 'anything', label: "I'm up for anything!", emoji: '✨' },
];

export const COUNTRIES = [
  'Afghanistan','Albania','Algeria','Argentina','Armenia','Australia','Austria','Azerbaijan',
  'Bahrain','Bangladesh','Belarus','Belgium','Bolivia','Bosnia and Herzegovina','Brazil','Bulgaria',
  'Cambodia','Canada','Chile','China','Colombia','Croatia','Cyprus','Czech Republic',
  'Denmark','Dominican Republic','Ecuador','Egypt','Estonia','Ethiopia',
  'Finland','France','Georgia','Germany','Ghana','Greece','Guatemala',
  'Hong Kong','Hungary','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy',
  'Japan','Jordan','Kazakhstan','Kenya','Kuwait','Latvia','Lebanon','Lithuania','Luxembourg',
  'Malaysia','Mexico','Morocco','Myanmar','Netherlands','New Zealand','Nigeria','North Korea','Norway',
  'Oman','Pakistan','Palestine','Panama','Peru','Philippines','Poland','Portugal',
  'Qatar','Romania','Russia','Saudi Arabia','Serbia','Singapore','Slovakia','Slovenia',
  'South Africa','South Korea','Spain','Sri Lanka','Sweden','Switzerland','Taiwan','Thailand',
  'Turkey','Ukraine','United Arab Emirates','United Kingdom','United States','Uzbekistan',
  'Venezuela','Vietnam','Yemen','Zimbabwe',
];

export const COUNTRY_CURRENCY = {
  'United States': '$', 'Canada': 'CA$', 'Australia': 'A$', 'New Zealand': 'NZ$',
  'United Kingdom': '£', 'Germany': '€', 'France': '€', 'Italy': '€', 'Spain': '€',
  'Portugal': '€', 'Netherlands': '€', 'Belgium': '€', 'Austria': '€', 'Ireland': '€',
  'Finland': '€', 'Greece': '€', 'Luxembourg': '€', 'Cyprus': '€', 'Slovakia': '€',
  'Slovenia': '€', 'Estonia': '€', 'Latvia': '€', 'Lithuania': '€', 'Croatia': '€',
  'Japan': '¥', 'China': '¥', 'South Korea': '₩',
  'India': '₹', 'Pakistan': '₨', 'Sri Lanka': 'Rs', 'Nepal': 'Rs', 'Bangladesh': '৳',
  'Russia': '₽', 'Ukraine': '₴', 'Belarus': 'Br',
  'Brazil': 'R$', 'Argentina': '$', 'Mexico': '$', 'Colombia': '$', 'Chile': '$',
  'Peru': 'S/', 'Venezuela': 'Bs', 'Dominican Republic': '$', 'Guatemala': 'Q',
  'Panama': 'B/.', 'Ecuador': '$', 'Bolivia': 'Bs',
  'Turkey': '₺', 'Israel': '₪', 'Saudi Arabia': '﷼', 'UAE': 'د.إ',
  'United Arab Emirates': 'د.إ', 'Qatar': '﷼', 'Kuwait': 'KD', 'Bahrain': 'BD',
  'Oman': '﷼', 'Jordan': 'JD', 'Lebanon': 'LL', 'Iraq': 'IQ', 'Iran': '﷼',
  'Egypt': 'E£', 'Morocco': 'MAD', 'Nigeria': '₦', 'Ghana': '₵', 'Kenya': 'KSh',
  'Ethiopia': 'Br', 'South Africa': 'R', 'Zimbabwe': 'Z$',
  'Sweden': 'kr', 'Norway': 'kr', 'Denmark': 'kr',
  'Switzerland': 'CHF', 'Poland': 'zł', 'Czech Republic': 'Kč', 'Hungary': 'Ft',
  'Romania': 'lei', 'Bulgaria': 'лв', 'Serbia': 'din', 'Bosnia and Herzegovina': 'KM',
  'Albania': 'L', 'North Macedonia': 'ден',
  'Singapore': 'S$', 'Hong Kong': 'HK$', 'Taiwan': 'NT$', 'Malaysia': 'RM',
  'Thailand': '฿', 'Vietnam': '₫', 'Indonesia': 'Rp', 'Philippines': '₱',
  'Myanmar': 'K', 'Cambodia': '₭',
  'Kazakhstan': '₸', 'Uzbekistan': "so'm", 'Azerbaijan': '₼', 'Armenia': '֏',
  'Georgia': '₾',
  'Afghanistan': '؋', 'Yemen': '﷼', 'Palestine': '₪',
  'Algeria': 'DA', 'Libya': 'LD',
  'North Korea': '₩',
};

export const getCurrencySymbol = (country) => COUNTRY_CURRENCY[country] || '$';

export const TOP_SIZES    = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
export const BOTTOM_SIZES = ['24', '25', '26', '27', '28', '29', '30', '32', 'XS', 'S', 'M', 'L', 'XL'];
export const SHOE_SIZES   = ['5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '11', '12'];
